site_name: Accumulated Genealogy Resources

nav:
    - Historical Photographers:
      - Cleveland: cleveland.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.critic

theme:
    name: material
    features: toc.integrate

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

extra_css:
  - stylesheets/tables.css